### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by DivineDominion**

### CODE REVIEW

**Comment by DivineDominion** [comment]
I see that there's some export stuff missing. Wait a second ;)

**Comment by DivineDominion** [comment]
I have added a custom modulemap/framework configuration file. Do you want to merge the changes to build settings with the `.xcconfig` files?

This deprecates #42

**Comment by Eitot** [comment]
Can this be merged?

**Comment by MiMo42** [comment]
No, unfortunately not. It has has conflicts in project file.

**Comment by Eitot** [comment]
@DivineDominion, you can resolve the conflicts? I also cannot build your branch due to conflicts with the modulemap.

**Comment by DivineDominion** [comment]
Sorry, I use a different code base now and don't have the time to fix this ;( Recreating what I've done from scratch should be simple, though.

**Pull request closed without merging**
